#!/bin/bash

FFMPEG="../ffmpeg*/ffmpeg"

while true; do 
	./rds_wav rds.wav "`curl -s http://fukushima/playlists/latest_track_clean.php`"
	$FFMPEG -hide_banner -loglevel warning -channel_layout mono -i rds.wav -ar 192000 -f s32le -acodec pcm_s32le -ac 2 rds.raw
	mv rds.raw playme.raw
	sleep 10
done

